import type { CrmProject, ProjectStatus } from "@/lib/types";
import { iso } from "@/lib/date-utils";

export const projectStatuses: ProjectStatus[] = [
  "Active",
  "On Hold",
  "Completed",
  "Cancelled",
];

export const projectMocks: CrmProject[] = [
  {
    id: "prj_001",
    name: "Automation Platform Implementation",
    description: "Full platform deployment across sales, marketing, and operations divisions.",
    customerName: "Techno Solutions",
    companyId: "c_001",
    dealId: "d_001",
    dealName: "Techno Automation Suite",
    ownerId: "u_1",
    ownerName: "Hussain Ali",
    startDate: iso(-30, "10:00"),
    estimatedEndDate: iso(60, "10:00"),
    actualEndDate: null,
    status: "Active",
    budget: 49900,
    spent: 24950,
    progress: 50,
    tags: ["platform", "migration", "integration"],
    contactId: "ct_001",
    contactName: "Ahmed Khan",
  },
  {
    id: "prj_002",
    name: "ERP Integration",
    description: "Integrate ERP system with finlonexa CRM for data sync.",
    customerName: "Skyline Retail",
    companyId: "c_006",
    dealId: "d_006",
    dealName: "Skyline Retail Omnichannel",
    ownerId: "u_4",
    ownerName: "Zain Malik",
    startDate: iso(-15, "14:00"),
    estimatedEndDate: iso(45, "14:00"),
    actualEndDate: null,
    status: "On Hold",
    budget: 15000,
    spent: 8500,
    progress: 57,
    tags: ["integration", "data-sync"],
    contactId: "ct_006",
    contactName: "Omar Farooq",
  },
  {
    id: "prj_003",
    name: "Customer Portal Redesign",
    description: "Redesign customer-facing portal with improved UX and self-service features.",
    customerName: "Nova Systems",
    companyId: "c_003",
    dealId: "d_003",
    dealName: "Nova Cloud Migration",
    ownerId: "u_3",
    ownerName: "Sara Ahmed",
    startDate: iso(-20, "09:00"),
    estimatedEndDate: iso(30, "09:00"),
    actualEndDate: null,
    status: "Active",
    budget: 25000,
    spent: 12000,
    progress: 48,
    tags: ["redesign", "UX", "self-service"],
    contactId: "ct_003",
    contactName: "John Smith",
  },
  {
    id: "prj_004",
    name: "Data Migration Project",
    description: "Migrate legacy customer data to the new finlonexa platform.",
    customerName: "Lotus Digital",
    companyId: "c_009",
    dealId: "d_009",
    dealName: "Lotus Digital Agency Suite",
    ownerId: "u_2",
    ownerName: "Ali Khan",
    startDate: iso(-10, "09:00"),
    estimatedEndDate: iso(20, "09:00"),
    actualEndDate: null,
    status: "Completed",
    budget: 12000,
    spent: 12000,
    progress: 100,
    tags: ["migration", "data"],
    contactId: "ct_009",
    contactName: "Hina Shah",
  },
  {
    id: "prj_005",
    name: "AI Chatbot Deployment",
    description: "Deploy AI-powered chatbot for customer support tier 1 queries.",
    customerName: "BrightWave",
    companyId: "c_002",
    dealId: "d_002",
    dealName: "BrightWave Growth Pack",
    ownerId: "u_5",
    ownerName: "Ayesha Siddiqui",
    startDate: iso(-5, "11:00"),
    estimatedEndDate: iso(30, "11:00"),
    actualEndDate: null,
    status: "Active",
    budget: 8000,
    spent: 3000,
    progress: 38,
    tags: ["AI", "chatbot", "support"],
    contactId: "ct_002",
    contactName: "Sarah Malik",
  },
];

export function getProjectById(id: string): CrmProject | undefined {
  return projectMocks.find((p) => p.id === id);
}