import type {
  CrmTask,
  TaskPriorityLevel,
  TaskStatus,
  TaskType,
  RelatedRecordType,
} from "@/lib/types";
import { iso } from "@/lib/date-utils";

export const taskTypes: TaskType[] = [
  "Call",
  "Email",
  "WhatsApp",
  "Meeting",
  "Follow-up",
  "Demo",
  "Proposal",
  "Internal",
  "Other",
];

export const taskStatuses: TaskStatus[] = ["Open", "In Progress", "Completed", "Cancelled"];

export const taskPriorities: TaskPriorityLevel[] = ["Low", "Medium", "High", "Urgent"];

const today = new Date();

function isoTodayDays(daysFromToday: number, time: string): string {
  const d = new Date(today);
  d.setDate(d.getDate() + daysFromToday);
  const parts = time.split(":").map(Number);
  d.setHours(parts[0] ?? 0, parts[1] ?? 0, 0, 0);
  return d.toISOString();
}

export const taskMocks: CrmTask[] = [
  {
    id: "tk_001",
    title: "Send formal proposal to Techno Solutions",
    description: "Starter + Growth plan, 12-month contract with onboarding.",
    type: "Proposal",
    priority: "High",
    status: "Open",
    ownerId: "u_1",
    ownerName: "Hussain Ali",
    dueDate: isoTodayDays(0, "11:00"),
    dueTime: "11:00",
    relatedType: "Lead",
    relatedId: "l_001",
    relatedName: "Ahmed Khan",
    createdAt: iso(3, "10:00"),
  },
  {
    id: "tk_002",
    title: "Follow-up call with BrightWave",
    description: "Re-confirm budget owner before proposal.",
    type: "Call",
    priority: "High",
    status: "Open",
    ownerId: "u_2",
    ownerName: "Ali Khan",
    dueDate: isoTodayDays(0, "14:30"),
    dueTime: "14:30",
    relatedType: "Contact",
    relatedId: "ct_002",
    relatedName: "Sarah Malik",
    createdAt: iso(2, "09:00"),
  },
  {
    id: "tk_003",
    title: "Demo meeting with Nova Systems",
    description: "Product walkthrough with CTO and infra team.",
    type: "Demo",
    priority: "Urgent",
    status: "In Progress",
    ownerId: "u_3",
    ownerName: "Sara Ahmed",
    dueDate: isoTodayDays(0, "15:00"),
    dueTime: "15:00",
    relatedType: "Lead",
    relatedId: "l_003",
    relatedName: "John Smith",
    createdAt: iso(4, "11:00"),
  },
  {
    id: "tk_004",
    title: "Send WhatsApp inventory checklist",
    description: "Share automation checklist to qualify need.",
    type: "WhatsApp",
    priority: "Medium",
    status: "Completed",
    ownerId: "u_4",
    ownerName: "Zain Malik",
    dueDate: isoTodayDays(-1, "12:00"),
    dueTime: "12:00",
    relatedType: "Lead",
    relatedId: "l_004",
    relatedName: "Fatima Noor",
    createdAt: iso(5, "16:00"),
    completedAt: isoTodayDays(-1, "12:10"),
  },
  {
    id: "tk_005",
    title: "Prepare board presentation for Skyline Retail",
    description: "Q4 deal summary with 3-year roadmap.",
    type: "Internal",
    priority: "Urgent",
    status: "Open",
    ownerId: "u_1",
    ownerName: "Hussain Ali",
    dueDate: isoTodayDays(-1, "14:00"),
    dueTime: "14:00",
    relatedType: "Deal",
    relatedId: "d_005",
    relatedName: "Skyline Enterprise Suite",
    createdAt: iso(2, "09:30"),
  },
  {
    id: "tk_006",
    title: "Book discovery call with FinEdge",
    description: "Qualify budget and timeline for reporting dashboards.",
    type: "Follow-up",
    priority: "Medium",
    status: "Open",
    ownerId: "u_2",
    ownerName: "Ali Khan",
    dueDate: isoTodayDays(1, "10:00"),
    dueTime: "10:00",
    relatedType: "Lead",
    relatedId: "l_008",
    relatedName: "Bilal Aziz",
    createdAt: iso(6, "13:00"),
  },
  {
    id: "tk_007",
    title: "Update deal health for Atlas Logistics",
    description: "Route optimization discussion stalled - re-engage.",
    type: "Internal",
    priority: "Medium",
    status: "In Progress",
    ownerId: "u_5",
    ownerName: "Ayesha Siddiqui",
    dueDate: isoTodayDays(1, "16:00"),
    dueTime: "16:00",
    relatedType: "Deal",
    relatedId: "d_010",
    relatedName: "Atlas Logistics Platform",
    createdAt: iso(1, "09:00"),
  },
  {
    id: "tk_008",
    title: "Email pricing overview to Mint E-commerce",
    description: "Share subscription billing plans.",
    type: "Email",
    priority: "Low",
    status: "Open",
    ownerId: "u_1",
    ownerName: "Hussain Ali",
    dueDate: isoTodayDays(2, "09:30"),
    dueTime: "09:30",
    relatedType: "Lead",
    relatedId: "l_011",
    relatedName: "Zoya Tariq",
    createdAt: iso(1, "15:00"),
  },
  {
    id: "tk_009",
    title: "Send implementation timeline to Techno Solutions",
    description: "Attach rollout plan for automation suite.",
    type: "Email",
    priority: "High",
    status: "Open",
    ownerId: "u_1",
    ownerName: "Hussain Ali",
    dueDate: isoTodayDays(2, "11:00"),
    dueTime: "11:00",
    relatedType: "Deal",
    relatedId: "d_001",
    relatedName: "Techno Automation Suite",
    createdAt: iso(3, "12:00"),
  },
  {
    id: "tk_010",
    title: "Contract review with Skyline Retail",
    description: "Review 3-year commitment terms with legal.",
    type: "Meeting",
    priority: "High",
    status: "Open",
    ownerId: "u_1",
    ownerName: "Hussain Ali",
    dueDate: isoTodayDays(3, "13:00"),
    dueTime: "13:00",
    relatedType: "Company",
    relatedId: "c_106",
    relatedName: "Skyline Retail",
    createdAt: iso(4, "10:00"),
  },
  {
    id: "tk_011",
    title: "Follow up on proposal with Lotus Digital",
    description: "Check status after viewed - no reply yet.",
    type: "Follow-up",
    priority: "Urgent",
    status: "Open",
    ownerId: "u_3",
    ownerName: "Sara Ahmed",
    dueDate: isoTodayDays(3, "14:00"),
    dueTime: "14:00",
    relatedType: "Lead",
    relatedId: "l_009",
    relatedName: "Hina Shah",
    createdAt: iso(2, "17:00"),
  },
  {
    id: "tk_012",
    title: "Qualification call with BuildPro",
    description: "Field team tracking - confirm decision authority.",
    type: "Call",
    priority: "Medium",
    status: "Open",
    ownerId: "u_5",
    ownerName: "Ayesha Siddiqui",
    dueDate: isoTodayDays(6, "09:30"),
    dueTime: "09:30",
    relatedType: "Lead",
    relatedId: "l_005",
    relatedName: "Ali Raza",
    createdAt: iso(5, "12:00"),
  },
  {
    id: "tk_013",
    title: "Send route optimization demo video",
    description: "Share pre-recorded demo for logistics.",
    type: "Email",
    priority: "Medium",
    status: "Completed",
    ownerId: "u_5",
    ownerName: "Ayesha Siddiqui",
    dueDate: isoTodayDays(7, "10:30"),
    dueTime: "10:30",
    relatedType: "Lead",
    relatedId: "l_010",
    relatedName: "Imran Qureshi",
    createdAt: iso(7, "11:00"),
    completedAt: isoTodayDays(7, "10:45"),
  },
  {
    id: "tk_014",
    title: "Add Ahmed Khan to newsletter campaign",
    description: "Enterprise automation newsletter list.",
    type: "Internal",
    priority: "Low",
    status: "Completed",
    ownerId: "u_2",
    ownerName: "Ali Khan",
    dueDate: isoTodayDays(1, "09:00"),
    dueTime: "09:00",
    relatedType: "Lead",
    relatedId: "l_001",
    relatedName: "Ahmed Khan",
    createdAt: iso(9, "10:00"),
    completedAt: isoTodayDays(1, "09:05"),
  },
  {
    id: "tk_015",
    title: "Proposal walkthrough with GreenTech",
    description: "Present platform features to operations team.",
    type: "Demo",
    priority: "Medium",
    status: "Open",
    ownerId: "u_4",
    ownerName: "Zain Malik",
    dueDate: isoTodayDays(4, "12:00"),
    dueTime: "12:00",
    relatedType: "Lead",
    relatedId: "l_004",
    relatedName: "Fatima Noor",
    createdAt: iso(3, "10:30"),
  },
  {
    id: "tk_016",
    title: "Review quotes for Q4 deals",
    description: "Validate discount levels before sending.",
    type: "Internal",
    priority: "Medium",
    status: "Open",
    ownerId: "u_1",
    ownerName: "Hussain Ali",
    dueDate: isoTodayDays(5, "17:00"),
    dueTime: "17:00",
    relatedType: "Deal",
    relatedId: "d_002",
    relatedName: "BrightWave Growth Pack",
    createdAt: iso(1, "14:00"),
  },
  {
    id: "tk_017",
    title: "Discovery call with Urban Kraft",
    description: "Brand storefront requirements and budget.",
    type: "Call",
    priority: "Low",
    status: "Open",
    ownerId: "u_4",
    ownerName: "Zain Malik",
    dueDate: isoTodayDays(2, "11:30"),
    dueTime: "11:30",
    relatedType: "Lead",
    relatedId: "l_007",
    relatedName: "Nadia Hameed",
    createdAt: iso(2, "08:55"),
  },
  {
    id: "tk_018",
    title: "Send security whitepaper to Lotus Digital",
    description: "White-label and API access for agency accounts.",
    type: "Email",
    priority: "High",
    status: "Completed",
    ownerId: "u_3",
    ownerName: "Sara Ahmed",
    dueDate: isoTodayDays(0, "09:00"),
    dueTime: "09:00",
    relatedType: "Lead",
    relatedId: "l_009",
    relatedName: "Hina Shah",
    createdAt: iso(2, "16:00"),
    completedAt: isoTodayDays(0, "09:30"),
  },
  {
    id: "tk_019",
    title: "Prepare contract draft for Skyline Retail",
    description: "3-year enterprise agreement with onboarding SLA.",
    type: "Proposal",
    priority: "Urgent",
    status: "Open",
    ownerId: "u_1",
    ownerName: "Hussain Ali",
    dueDate: isoTodayDays(2, "10:00"),
    dueTime: "10:00",
    relatedType: "Deal",
    relatedId: "d_006",
    relatedName: "Skyline Retail Omnichannel",
    createdAt: iso(1, "11:00"),
  },
  {
    id: "tk_020",
    title: "Setup new-user onboarding for Mint E-commerce",
    description: "Prepare onboarding sequence for subscription billing.",
    type: "Internal",
    priority: "Low",
    status: "Cancelled",
    ownerId: "u_1",
    ownerName: "Hussain Ali",
    dueDate: isoTodayDays(3, "09:00"),
    dueTime: "09:00",
    relatedType: "Lead",
    relatedId: "l_011",
    relatedName: "Zoya Tariq",
    createdAt: iso(8, "10:00"),
  },
  {
    id: "tk_021",
    title: "Send marketing performance checklist",
    description: "Download gate follow-up for BrightWave.",
    type: "Email",
    priority: "Medium",
    status: "Open",
    ownerId: "u_2",
    ownerName: "Ali Khan",
    dueDate: isoTodayDays(1, "15:00"),
    dueTime: "15:00",
    relatedType: "Company",
    relatedId: "c_102",
    relatedName: "BrightWave",
    createdAt: iso(4, "14:00"),
  },
  {
    id: "tk_022",
    title: "Follow up on cloud migration timing with Nova Systems",
    description: "Confirm Q1 migration timeline.",
    type: "Follow-up",
    priority: "Medium",
    status: "Open",
    ownerId: "u_3",
    ownerName: "Sara Ahmed",
    dueDate: isoTodayDays(3, "13:00"),
    dueTime: "13:00",
    relatedType: "Company",
    relatedId: "c_103",
    relatedName: "Nova Systems",
    createdAt: iso(1, "10:30"),
  },
];

export function getTaskById(id: string): CrmTask | undefined {
  return taskMocks.find((task) => task.id === id);
}

export function tasksByRelated(type: RelatedRecordType, id: string): CrmTask[] {
  return taskMocks.filter((task) => task.relatedType === type && task.relatedId === id);
}

export function ownerTaskCounts() {
  const counts: Record<string, number> = {};
  for (const task of taskMocks) {
    if (task.status !== "Completed" && task.status !== "Cancelled") {
      counts[task.ownerName] = (counts[task.ownerName] ?? 0) + 1;
    }
  }
  return counts;
}