import type { CrmInvoice, InvoiceStatus } from "@/lib/types";
import { iso } from "@/lib/date-utils";

export const invoiceStatuses: InvoiceStatus[] = [
  "Draft",
  "Sent",
  "Paid",
  "Overdue",
  "Cancelled",
];

export const invoiceMocks: CrmInvoice[] = [
  {
    id: "inv_001",
    number: "INV-2024-001",
    customerName: "Techno Solutions",
    companyId: "c_001",
    dealId: "d_001",
    dealName: "Techno Automation Suite",
    issueDate: iso(-10, "10:00"),
    dueDate: iso(-5, "10:00"),
    status: "Overdue",
    currency: "USD",
    subtotal: 14990,
    discount: 0,
    tax: 2248.5,
    total: 17238.5,
    paymentStatus: "Unpaid",
    paymentMethod: null,
    terms: "Net 30",
    notes: "Final invoice for Automation Suite implementation",
    lineItems: [
      {
        id: "ili_001",
        description: "Enterprise Automation Suite - Annual License",
        quantity: 1,
        unitPrice: 9990,
        discount: 0,
        taxRate: 0.15,
        taxAmount: 1498.5,
        total: 11488.5,
      },
      {
        id: "ili_002",
        description: "Implementation Services - 20 hours",
        quantity: 20,
        unitPrice: 199,
        discount: 0,
        taxRate: 0.15,
        taxAmount: 59.7,
        total: 4193,
      },
    ],
    timeline: [
      { event: "Invoice drafted", at: iso(-10, "10:00") },
      { event: "Invoice sent", at: iso(-8, "14:00") },
      { event: "Payment due", at: iso(-5, "10:00") },
    ],
  },
  {
    id: "inv_002",
    number: "INV-2024-002",
    customerName: "Skyline Retail",
    companyId: "c_006",
    dealId: "d_006",
    dealName: "Skyline Retail Omnichannel",
    issueDate: iso(0, "14:00"),
    dueDate: iso(30, "14:00"),
    status: "Sent",
    currency: "USD",
    subtotal: 5680,
    discount: 568,
    tax: 538.2,
    total: 6442,
    paymentStatus: "Partially Paid",
    paymentMethod: "Credit Card",
    terms: "Net 15",
    notes: "Pending partial payment",
    lineItems: [
      {
        id: "ili_003",
        description: "Integration Pack - 2 licenses",
        quantity: 2,
        unitPrice: 2990,
        discount: 0.1,
        taxRate: 0.15,
        taxAmount: 538.2,
        total: 5680,
      },
    ],
    timeline: [
      { event: "Invoice drafted", at: iso(0, "10:00") },
      { event: "Invoice sent", at: iso(0, "14:00") },
    ],
  },
  {
    id: "inv_003",
    number: "INV-2024-003",
    customerName: "Nova Systems",
    companyId: "c_003",
    dealId: "d_003",
    dealName: "Nova Cloud Migration",
    issueDate: iso(5, "11:00"),
    dueDate: iso(20, "11:00"),
    status: "Paid",
    currency: "USD",
    subtotal: 145,
    discount: 0,
    tax: 34.8,
    total: 179.8,
    paymentStatus: "Paid",
    paymentMethod: "Bank Transfer",
    terms: "Net 21",
    notes: "Payment received",
    lineItems: [
      {
        id: "ili_004",
        description: "Basic Plan - 5 seats",
        quantity: 5,
        unitPrice: 29,
        discount: 0,
        taxRate: 0.12,
        taxAmount: 34.8,
        total: 179.8,
      },
    ],
    timeline: [
      { event: "Invoice drafted", at: iso(5, "11:00") },
      { event: "Invoice sent", at: iso(5, "14:00") },
      { event: "Payment received", at: iso(15, "10:00") },
    ],
  },
  {
    id: "inv_004",
    number: "INV-2024-004",
    customerName: "Lotus Digital",
    companyId: "c_009",
    dealId: "d_009",
    dealName: "Lotus Digital Agency Suite",
    issueDate: iso(-15, "11:00"),
    dueDate: iso(-10, "11:00"),
    status: "Cancelled",
    currency: "USD",
    subtotal: 1188,
    discount: 0,
    tax: 118.8,
    total: 1306.8,
    paymentStatus: "Refunded",
    paymentMethod: null,
    terms: "Net 14",
    notes: "Customer cancelled subscription",
    lineItems: [
      {
        id: "ili_005",
        description: "Monthly Subscription - 12 months",
        quantity: 12,
        unitPrice: 99,
        discount: 0,
        taxRate: 0.1,
        taxAmount: 118.8,
        total: 1306.8,
      },
    ],
    timeline: [
      { event: "Invoice drafted", at: iso(-15, "11:00") },
      { event: "Invoice sent", at: iso(-14, "14:00") },
      { event: "Invoice cancelled", at: iso(-10, "10:00") },
    ],
  },
];

export function getInvoiceById(id: string): CrmInvoice | undefined {
  return invoiceMocks.find((i) => i.id === id);
}