import type { SalesGoal } from "@/lib/types";

export const goalMocks: SalesGoal[] = [
  {
    id: "goal_001",
    type: "Revenue",
    ownerId: "u_1",
    ownerName: "Hussain Ali",
    team: "Enterprise",
    period: "Quarterly",
    target: 500000,
    current: 342000,
    currency: "USD",
  },
  {
    id: "goal_002",
    type: "Deals Won",
    ownerId: "u_3",
    ownerName: "Sara Ahmed",
    team: "Mid-Market",
    period: "Quarterly",
    target: 18,
    current: 15,
  },
  {
    id: "goal_003",
    type: "New Leads",
    ownerId: "u_2",
    ownerName: "Ali Khan",
    team: "SDR Team",
    period: "Monthly",
    target: 120,
    current: 81,
  },
  {
    id: "goal_004",
    type: "Meetings",
    ownerId: "u_5",
    ownerName: "Ayesha Siddiqui",
    team: "SDR Team",
    period: "Monthly",
    target: 40,
    current: 28,
  },
  {
    id: "goal_005",
    type: "Calls",
    ownerId: "u_4",
    ownerName: "Zain Malik",
    period: "Monthly",
    target: 200,
    current: 96,
  },
  {
    id: "goal_006",
    type: "Revenue",
    ownerId: "u_2",
    ownerName: "Ali Khan",
    team: "SMB",
    period: "Annual",
    target: 1500000,
    current: 1120000,
    currency: "USD",
  },
];