import type { CrmSupportTicket, SupportStatus, SupportPriority } from "@/lib/types";
import { iso } from "@/lib/date-utils";

export const supportStatuses: SupportStatus[] = [
  "Open",
  "In Progress",
  "Resolved",
  "Closed",
];

export const supportPriorities: SupportPriority[] = [
  "Low",
  "Medium",
  "High",
  "Urgent",
];

export const supportTicketMocks: CrmSupportTicket[] = [
  {
    id: "st_001",
    title: "Integration Issue",
    description: "API returning 500 errors when attempting to sync contacts.",
    customerName: "Techno Solutions",
    companyId: "c_001",
    dealId: "d_001",
    dealName: "Techno Automation Suite",
    ownerId: "u_1",
    ownerName: "Hussain Ali",
    team: "Engineering",
    status: "Open",
    priority: "High",
    tags: ["API", "contacts", "sync"],
    source: "Email",
    channel: "Email",
    relatedTicketId: null,
    relatedDealId: "d_001",
    relatedContactId: "ct_001",
    relatedContactName: "Ahmed Khan",
    createdAt: iso(-10, "10:00"),
    updatedAt: iso(-5, "14:00"),
    resolvedAt: null,
    closedAt: null,
    slaDue: iso(-3, "10:00"),
    slaMet: false,
    notes: "Last sync failed at 09:45. Error: Invalid token.",
    activityLog: [
      { at: iso(-10, "10:00"), action: "Ticket created", author: "Hussain Ali" },
      { at: iso(-5, "14:00"), action: "Comment added", author: "Engineering Team" },
    ],
  },
  {
    id: "st_002",
    title: "Password Reset Request",
    description: "Customer cannot log in to the platform.",
    customerName: "Skyline Retail",
    companyId: "c_006",
    dealId: "d_006",
    dealName: "Skyline Retail Omnichannel",
    ownerId: "u_4",
    ownerName: "Zain Malik",
    team: "Support",
    status: "In Progress",
    priority: "Medium",
    tags: ["login", "password", "reset"],
    source: "Web Form",
    channel: "Web",
    relatedTicketId: null,
    relatedDealId: "d_006",
    relatedContactId: "ct_006",
    relatedContactName: "Omar Farooq",
    createdAt: iso(-3, "09:00"),
    updatedAt: iso(-1, "10:00"),
    resolvedAt: null,
    closedAt: null,
    slaDue: iso(2, "09:00"),
    slaMet: true,
    notes: "Reset link sent to Omar's email.",
    activityLog: [
      { at: iso(-3, "09:00"), action: "Ticket created", author: "Zain Malik" },
      { at: iso(-1, "10:00"), action: "Reset link sent", author: "Support Agent" },
    ],
  },
  {
    id: "st_003",
    title: "Feature Request: Custom Reporting",
    description: "Need ability to export custom report fields from CRM.",
    customerName: "Nova Systems",
    companyId: "c_003",
    dealId: "d_003",
    dealName: "Nova Cloud Migration",
    ownerId: "u_3",
    ownerName: "Sara Ahmed",
    team: "Product",
    status: "Resolved",
    priority: "Low",
    tags: ["feature", "reporting", "export"],
    source: "Product Feedback",
    channel: "Feedback Form",
    relatedTicketId: null,
    relatedDealId: "d_003",
    relatedContactId: "ct_003",
    relatedContactName: "John Smith",
    createdAt: iso(-20, "11:00"),
    updatedAt: iso(-5, "14:00"),
    resolvedAt: iso(-2, "14:00"),
    closedAt: iso(-1, "10:00"),
    slaDue: iso(-10, "11:00"),
    slaMet: true,
    notes: "Added to product backlog for Q4 release.",
    activityLog: [
      { at: iso(-20, "11:00"), action: "Ticket created", author: "Sara Ahmed" },
      { at: iso(-5, "14:00"), action: "Resolved - added to backlog", author: "Product Team" },
      { at: iso(-1, "10:00"), action: "Ticket closed", author: "Sara Ahmed" },
    ],
  },
  {
    id: "st_004",
    title: "Performance Degradation",
    description: "CRM dashboard loading slowly with large data sets.",
    customerName: "Lotus Digital",
    companyId: "c_009",
    dealId: "d_009",
    dealName: "Lotus Digital Agency Suite",
    ownerId: "u_2",
    ownerName: "Ali Khan",
    team: "Engineering",
    status: "Closed",
    priority: "Urgent",
    tags: ["performance", "dashboard", "slow"],
    source: "Internal",
    channel: "Internal",
    relatedTicketId: null,
    relatedDealId: "d_009",
    relatedContactId: "ct_009",
    relatedContactName: "Hina Shah",
    createdAt: iso(-15, "11:00"),
    updatedAt: iso(-2, "14:00"),
    resolvedAt: iso(-1, "14:00"),
    closedAt: iso(0, "10:00"),
    slaDue: iso(-5, "11:00"),
    slaMet: true,
    notes: "Fixed by optimizing database queries.",
    activityLog: [
      { at: iso(-15, "11:00"), action: "Ticket created", author: "Ali Khan" },
      { at: iso(-2, "14:00"), action: "Resolved - DB queries optimized", author: "Engineering Team" },
      { at: iso(0, "10:00"), action: "Ticket closed", author: "Ali Khan" },
    ],
  },
];

export function getTicketById(id: string): CrmSupportTicket | undefined {
  return supportTicketMocks.find((t) => t.id === id);
}