import type { Conversation, EmailTemplate, ThreadMessage } from "@/lib/types";
import { iso } from "@/lib/date-utils";

export const inboxChannels = ["Email", "WhatsApp", "SMS", "Call"] as const;

export const inboxConversations: Conversation[] = [
  {
    id: "cv_001",
    channel: "Email",
    contactId: "ct_001",
    contactName: "Ahmed Khan",
    companyId: "c_101",
    companyName: "Techno Solutions",
    subject: "Re: Automation Suite — next steps",
    preview: "Hi Hussain, thanks for the walkthrough. We need the implementation timeline...",
    lastMessageAt: iso(0, "09:41"),
    unreadCount: 2,
    assignedToId: "u_1",
    assignedToName: "Hussain Ali",
    priority: "High",
    tags: ["decision-maker", "proposal"],
    openDeals: ["d_001"],
    openDealValue: 42000,
    status: "open",
  },
  {
    id: "cv_002",
    channel: "WhatsApp",
    contactId: "ct_010",
    contactName: "Imran Qureshi",
    companyId: "c_110",
    companyName: "Atlas Logistics",
    preview: "Great, send over the fleet module demo link whenever you're ready...",
    lastMessageAt: iso(0, "10:05"),
    unreadCount: 1,
    assignedToId: "u_5",
    assignedToName: "Ayesha Siddiqui",
    priority: "Medium",
    tags: ["demo-requested"],
    openDeals: ["d_010"],
    openDealValue: 61000,
    status: "open",
  },
  {
    id: "cv_003",
    channel: "SMS",
    contactId: "ct_004",
    contactName: "Fatima Noor",
    companyId: "c_104",
    companyName: "GreenTech",
    preview: "Can we push the proposal walkthrough to next Tuesday?",
    lastMessageAt: iso(0, "08:12"),
    unreadCount: 1,
    assignedToId: "u_4",
    assignedToName: "Zain Malik",
    priority: "Medium",
    tags: ["reschedule"],
    openDeals: ["d_004"],
    openDealValue: 38000,
    status: "pending",
  },
  {
    id: "cv_004",
    channel: "Email",
    contactId: "ct_003",
    contactName: "John Smith",
    companyId: "c_103",
    companyName: "Nova Systems",
    subject: "Cloud Migration — pricing question",
    preview: "Hi, do you have a breakdown of the migration services outside the platform subscription?...",
    lastMessageAt: iso(-1, "16:30"),
    unreadCount: 0,
    assignedToId: "u_3",
    assignedToName: "Sara Ahmed",
    priority: "High",
    tags: ["pricing"],
    openDeals: ["d_003"],
    openDealValue: 54000,
    status: "open",
  },
  {
    id: "cv_005",
    channel: "WhatsApp",
    contactId: "ct_006",
    contactName: "Omar Farooq",
    companyId: "c_106",
    companyName: "Skyline Retail",
    preview: "Attachment received — CFO has reviewed the 3-year terms ✔",
    lastMessageAt: iso(-1, "13:02"),
    unreadCount: 0,
    assignedToId: "u_1",
    assignedToName: "Hussain Ali",
    priority: "High",
    tags: ["contract", "decision-maker"],
    openDeals: ["d_006"],
    openDealValue: 150000,
    status: "open",
  },
  {
    id: "cv_006",
    channel: "Email",
    contactId: "ct_009",
    contactName: "Hina Shah",
    companyId: "c_109",
    companyName: "Lotus Digital",
    subject: "Security whitepaper received",
    preview: "Thanks for the whitepaper. Our security team has a few questions about SSO...",
    lastMessageAt: iso(-2, "11:00"),
    unreadCount: 0,
    assignedToId: "u_3",
    assignedToName: "Sara Ahmed",
    priority: "Medium",
    tags: ["security"],
    openDeals: ["d_009"],
    openDealValue: 29000,
    status: "pending",
  },
  {
    id: "cv_007",
    channel: "Call",
    contactId: "ct_002",
    contactName: "Sarah Malik",
    companyId: "c_102",
    companyName: "BrightWave",
    preview: "Voicemail left — call back for budget owner details",
    lastMessageAt: iso(-1, "09:20"),
    unreadCount: 0,
    assignedToId: "u_2",
    assignedToName: "Ali Khan",
    priority: "Low",
    tags: ["follow-up"],
    openDeals: ["d_002"],
    openDealValue: 24000,
    status: "open",
  },
  {
    id: "cv_008",
    channel: "WhatsApp",
    contactId: "ct_005",
    contactName: "Ali Raza",
    companyId: "c_105",
    companyName: "BuildPro",
    preview: "Send the field tracking app screenshots when possible",
    lastMessageAt: iso(-2, "17:30"),
    unreadCount: 0,
    assignedToId: "u_5",
    assignedToName: "Ayesha Siddiqui",
    priority: "Low",
    tags: ["materials"],
    openDeals: ["d_005"],
    openDealValue: 33000,
    status: "closed",
  },
  {
    id: "cv_009",
    channel: "SMS",
    contactId: "ct_007",
    contactName: "Nadia Hameed",
    companyId: "c_107",
    companyName: "Urban Kraft",
    preview: "Thanks for the note — talk soon.",
    lastMessageAt: iso(-3, "08:55"),
    unreadCount: 0,
    assignedToId: "u_4",
    assignedToName: "Zain Malik",
    priority: "Low",
    tags: [],
    openDeals: ["d_007"],
    openDealValue: 28000,
    status: "closed",
  },
];

export const threadByConversation: Record<string, ThreadMessage[]> = {
  cv_001: [
    {
      id: "tm_001",
      conversationId: "cv_001",
      direction: "in",
      authorName: "Ahmed Khan",
      authorEmail: "ahmed.khan@technosolutions.com",
      content:
        "Hi Hussain, thanks for the walkthrough. We really liked the approval workflow and audit logs. We need the implementation timeline and a phased rollout plan before we commit.",
      channel: "Email",
      sentAt: iso(-1, "09:12"),
      status: "opened",
    },
    {
      id: "tm_002",
      conversationId: "cv_001",
      direction: "out",
      authorName: "Hussain Ali",
      authorEmail: "hussain.ali@relvo.io",
      content:
        "Hi Ahmed, great to hear. I'll share the implementation timeline with a suggested phased rollout (Phase 1: core + approvals, Phase 2: migrations). Expect it by Thursday morning.",
      channel: "Email",
      sentAt: iso(-1, "10:00"),
      status: "opened",
    },
    {
      id: "tm_003",
      conversationId: "cv_001",
      direction: "in",
      authorName: "Ahmed Khan",
      authorEmail: "ahmed.khan@technosolutions.com",
      content:
        "Perfect. Also, procurement asked for SSO and audit logs — those are must-haves. Can you confirm support out of the box?",
      channel: "Email",
      sentAt: iso(0, "09:38"),
      status: "opened",
    },
    {
      id: "tm_004",
      conversationId: "cv_001",
      direction: "in",
      authorName: "Ahmed Khan",
      authorEmail: "ahmed.khan@technosolutions.com",
      content: "SSO (SAML), audit logs, and role-based permissions are all included in the Enterprise plan. I'll add the enablement guide to the timeline email.",
      channel: "Email",
      sentAt: iso(0, "09:41"),
      status: "opened",
    },
  ],
  cv_002: [
    {
      id: "tm_005",
      conversationId: "cv_002",
      direction: "in",
      authorName: "Imran Qureshi",
      content: "Great, send over the fleet module demo link whenever you're ready. Our ops team has 15 minutes tomorrow at 4 PM.",
      channel: "WhatsApp",
      sentAt: iso(0, "10:05"),
      status: "delivered",
    },
  ],
  cv_003: [
    {
      id: "tm_006",
      conversationId: "cv_003",
      direction: "in",
      authorName: "Fatima Noor",
      content: "Can we push the proposal walkthrough to next Tuesday? A conflict came up this week.",
      channel: "SMS",
      sentAt: iso(0, "08:12"),
      status: "delivered",
    },
  ],
  cv_004: [
    {
      id: "tm_007",
      conversationId: "cv_004",
      direction: "in",
      authorName: "John Smith",
      authorEmail: "john.smith@novasystems.io",
      content:
        "Hi, do you have a breakdown of the migration services outside the platform subscription? Our CFO wants a line-item estimate before we proceed.",
      channel: "Email",
      sentAt: iso(-1, "16:30"),
      status: "opened",
    },
  ],
  cv_005: [
    {
      id: "tm_008",
      conversationId: "cv_005",
      direction: "in",
      authorName: "Omar Farooq",
      content: "Attachment received — CFO has reviewed the 3-year terms ✔ Can we schedule the contract signing for next week?",
      channel: "WhatsApp",
      sentAt: iso(-1, "13:02"),
      status: "replied",
    },
  ],
  cv_007: [
    {
      id: "tm_009",
      conversationId: "cv_007",
      direction: "in",
      authorName: "Sarah Malik",
      content: "Voicemail received — please call back regarding budget owner availability.",
      channel: "Call",
      sentAt: iso(-1, "09:20"),
      status: "delivered",
    },
  ],
};

export const emailTemplates: EmailTemplate[] = [
  {
    id: "et_001",
    name: "Implementation Timeline",
    subject: "Implementation timeline for {{company}}",
    body: "Hi {{contact}},\n\nAs promised, here is the phased implementation timeline for {{company}}. Phase 1 covers onboarding, permissions and approvals. Phase 2 covers data migration and integrations.\n\nLet me know if you'd like any adjustments.\n\nBest regards,\n{{owner}}",
    category: "Proposal",
  },
  {
    id: "et_002",
    name: "Proposal Follow-up",
    subject: "Following up on the proposal",
    body: "Hi {{contact}},\n\nI wanted to follow up on the proposal we shared. Do you have any questions, or should we schedule a walkthrough?\n\nBest,\n{{owner}}",
    category: "Follow-up",
  },
  {
    id: "et_003",
    name: "Pricing Breakdown",
    subject: "Pricing breakdown — {{company}}",
    body: "Hi {{contact}},\n\nPlease find the requested pricing breakdown below. We separate platform fees from implementation and migration services.\n\nHappy to walk through it.\n\nBest,\n{{owner}}",
    category: "Sales",
  },
  {
    id: "et_004",
    name: "Demo Recap",
    subject: "Recap of our demo",
    body: "Hi {{contact}},\n\nThanks for your time today. Here's a quick recap of the demo and the items we discussed. The recording and enablement guide are attached.\n\nBest,\n{{owner}}",
    category: "Demo",
  },
  {
    id: "et_005",
    name: "Security Whitepaper",
    subject: "Security & compliance overview",
    body: "Hi {{contact}},\n\nAs requested, here's our security whitepaper covering SSO (SAML), audit logs, encryption, and our compliance posture.\n\nHappy to schedule a security deep-dive.\n\nBest,\n{{owner}}",
    category: "Security",
  },
  {
    id: "et_006",
    name: "Contract Terms",
    subject: "Contract terms — {{company}}",
    body: "Hi {{contact}},\n\nAttached are the contract terms aligned with the 3-year plan we discussed. Please review and let me know your questions.\n\nBest,\n{{owner}}",
    category: "Contract",
  },
];

export function getConversation(id: string): Conversation | undefined {
  return inboxConversations.find((c) => c.id === id);
}

export function getThread(conversationId: string): ThreadMessage[] {
  return threadByConversation[conversationId] ?? [];
}

export function unreadConversationCount(): number {
  return inboxConversations.filter((c) => c.unreadCount > 0).length;
}

export function inboxChannelLabel(channel: Conversation["channel"]): string {
  if (channel === "Call") return "Call";
  if (channel === "WhatsApp") return "WhatsApp";
  if (channel === "SMS") return "SMS";
  return "Email";
}