import type { SubscriptionRecord } from "@/lib/types";
import { iso } from "@/lib/date-utils";

export const subscriptionMocks: SubscriptionRecord[] = [
  {
    id: "sub_001",
    customerId: "cus_1",
    customerName: "Acme Motors",
    companyId: "com_1",
    companyName: "Acme Motors",
    plan: "Enterprise",
    amount: 2490,
    currency: "USD",
    billingCycle: "Monthly",
    startDate: iso(-220, "09:00"),
    renewalDate: iso(8, "09:00"),
    status: "Active",
  },
  {
    id: "sub_002",
    customerId: "cus_2",
    customerName: "Nova Systems",
    companyId: "com_2",
    companyName: "Nova Systems",
    plan: "Growth",
    amount: 990,
    currency: "USD",
    billingCycle: "Quarterly",
    startDate: iso(-160, "09:00"),
    renewalDate: iso(25, "09:00"),
    status: "Active",
  },
  {
    id: "sub_003",
    customerId: "cus_3",
    customerName: "Skyline Retail",
    companyId: "com_3",
    companyName: "Skyline Retail",
    plan: "Starter",
    amount: 299,
    currency: "USD",
    billingCycle: "Monthly",
    startDate: iso(-90, "09:00"),
    renewalDate: iso(3, "09:00"),
    status: "Past Due",
  },
  {
    id: "sub_004",
    customerId: "cus_4",
    customerName: "BrightWave Media",
    companyId: "com_4",
    companyName: "BrightWave Media",
    plan: "Growth",
    amount: 990,
    currency: "USD",
    billingCycle: "Yearly",
    startDate: iso(-310, "09:00"),
    renewalDate: iso(55, "09:00"),
    status: "Trial",
  },
  {
    id: "sub_005",
    customerId: "cus_5",
    customerName: "Lotus Digital",
    companyId: "com_5",
    companyName: "Lotus Digital",
    plan: "Starter",
    amount: 2990,
    currency: "USD",
    billingCycle: "Yearly",
    startDate: iso(-420, "09:00"),
    renewalDate: iso(145, "09:00"),
    status: "Active",
  },
  {
    id: "sub_006",
    customerId: "cus_6",
    customerName: "Echo Furnishings",
    companyId: "com_6",
    companyName: "Echo Furnishings",
    plan: "Growth",
    amount: 990,
    currency: "USD",
    billingCycle: "Monthly",
    startDate: iso(-320, "09:00"),
    renewalDate: iso(-15, "09:00"),
    status: "Cancelled",
  },
];