import type { CallRecord, CallDirection, CallOutcome } from "@/lib/types";

export const callDirections: CallDirection[] = ["Inbound", "Outbound"];

export const callOutcomes: CallOutcome[] = [
  "Connected",
  "No Answer",
  "Voicemail",
  "Busy",
  "Follow-up Needed",
];

const today = new Date();

function isoTodayDays(daysFromToday: number, time: string): string {
  const d = new Date(today);
  d.setDate(d.getDate() + daysFromToday);
  const parts = time.split(":").map(Number);
  d.setHours(parts[0] ?? 0, parts[1] ?? 0, 0, 0);
  return d.toISOString();
}

export const callMocks: CallRecord[] = [
  {
    id: "cl_001",
    contactId: "ct_001",
    contactName: "Ahmed Khan",
    companyId: "c_101",
    companyName: "Techno Solutions",
    relatedDealId: "d_001",
    relatedDealName: "Techno Automation Suite",
    direction: "Outbound",
    duration: 22,
    date: isoTodayDays(-7, "11:00"),
    time: "11:00",
    ownerId: "u_1",
    ownerName: "Hussain Ali",
    outcome: "Connected",
    notes: "Discovery call. BANT confirmed, next step proposal.",
  },
  {
    id: "cl_002",
    contactId: "ct_002",
    contactName: "Sarah Malik",
    companyId: "c_102",
    companyName: "BrightWave",
    relatedDealId: "d_002",
    relatedDealName: "BrightWave Growth Pack",
    direction: "Outbound",
    duration: 14,
    date: isoTodayDays(-3, "09:20"),
    time: "09:20",
    ownerId: "u_2",
    ownerName: "Ali Khan",
    outcome: "Follow-up Needed",
    notes: "Budget owner unavailable. Schedule follow-up next week.",
  },
  {
    id: "cl_003",
    contactId: "ct_010",
    contactName: "Imran Qureshi",
    companyId: "c_110",
    companyName: "Atlas Logistics",
    relatedDealId: "d_010",
    relatedDealName: "Atlas Logistics Platform",
    direction: "Outbound",
    duration: 18,
    date: isoTodayDays(-3, "11:50"),
    time: "11:50",
    ownerId: "u_5",
    ownerName: "Ayesha Siddiqui",
    outcome: "Connected",
    notes: "Intro call on fleet size and route optimization.",
  },
  {
    id: "cl_004",
    contactId: "ct_006",
    contactName: "Omar Farooq",
    companyId: "c_106",
    companyName: "Skyline Retail",
    relatedDealId: "d_006",
    relatedDealName: "Skyline Retail Omnichannel",
    direction: "Inbound",
    duration: 31,
    date: isoTodayDays(-2, "16:10"),
    time: "16:10",
    ownerId: "u_1",
    ownerName: "Hussain Ali",
    outcome: "Connected",
    notes: "Inbound Q&A on omnichannel rollout plan.",
  },
  {
    id: "cl_005",
    contactId: "ct_004",
    contactName: "Fatima Noor",
    companyId: "c_104",
    companyName: "GreenTech",
    relatedDealId: "d_004",
    relatedDealName: "GreenTech Inventory",
    direction: "Outbound",
    duration: 0,
    date: isoTodayDays(-1, "10:15"),
    time: "10:15",
    ownerId: "u_4",
    ownerName: "Zain Malik",
    outcome: "No Answer",
    notes: "",
  },
  {
    id: "cl_006",
    contactId: "ct_005",
    contactName: "Ali Raza",
    companyId: "c_105",
    companyName: "BuildPro",
    relatedDealId: "d_005",
    relatedDealName: "BuildPro Field Tracking",
    direction: "Outbound",
    duration: 8,
    date: isoTodayDays(-6, "17:30"),
    time: "17:30",
    ownerId: "u_5",
    ownerName: "Ayesha Siddiqui",
    outcome: "Voicemail",
    notes: "Left message about field team tracking demo.",
  },
  {
    id: "cl_007",
    contactId: "ct_009",
    contactName: "Hina Shah",
    companyId: "c_109",
    companyName: "Lotus Digital",
    relatedDealId: "d_009",
    relatedDealName: "Lotus Digital Agency Suite",
    direction: "Inbound",
    duration: 12,
    date: isoTodayDays(-2, "09:05"),
    time: "09:05",
    ownerId: "u_3",
    ownerName: "Sara Ahmed",
    outcome: "Connected",
    notes: "Quick check-in on security whitepaper attachment.",
  },
  {
    id: "cl_008",
    contactId: "ct_011",
    contactName: "Zoya Tariq",
    companyId: "c_111",
    companyName: "Mint E-commerce",
    relatedDealId: "d_011",
    relatedDealName: "Mint Subscription Billing",
    direction: "Outbound",
    duration: 0,
    date: isoTodayDays(0, "10:02"),
    time: "10:02",
    ownerId: "u_1",
    ownerName: "Hussain Ali",
    outcome: "Busy",
    notes: "Will call back tomorrow morning.",
  },
  {
    id: "cl_009",
    contactId: "ct_008",
    contactName: "Bilal Aziz",
    companyId: "c_108",
    companyName: "FinEdge",
    relatedDealId: "d_008",
    relatedDealName: "FinEdge Reporting",
    direction: "Outbound",
    duration: 9,
    date: isoTodayDays(-4, "14:15"),
    time: "14:15",
    ownerId: "u_2",
    ownerName: "Ali Khan",
    outcome: "Voicemail",
    notes: "Budget and timeline check-in.",
  },
  {
    id: "cl_010",
    contactId: "ct_007",
    contactName: "Nadia Hameed",
    companyId: "c_107",
    companyName: "Urban Kraft",
    relatedDealId: "d_007",
    relatedDealName: "Urban Kraft Storefront",
    direction: "Inbound",
    duration: 6,
    date: isoTodayDays(-1, "08:55"),
    time: "08:55",
    ownerId: "u_4",
    ownerName: "Zain Malik",
    outcome: "Connected",
    notes: "Inbound about storefront launch timing.",
  },
  {
    id: "cl_011",
    contactId: "ct_003",
    contactName: "John Smith",
    companyId: "c_103",
    companyName: "Nova Systems",
    relatedDealId: "d_003",
    relatedDealName: "Nova Cloud Migration",
    direction: "Outbound",
    duration: 35,
    date: isoTodayDays(-1, "10:00"),
    time: "10:00",
    ownerId: "u_3",
    ownerName: "Sara Ahmed",
    outcome: "Connected",
    notes: "Discovery call - implementation timeline discussion.",
  },
  {
    id: "cl_012",
    contactId: "ct_001",
    contactName: "Ahmed Khan",
    companyId: "c_101",
    companyName: "Techno Solutions",
    relatedDealId: "d_001",
    relatedDealName: "Techno Automation Suite",
    direction: "Outbound",
    duration: 0,
    date: isoTodayDays(1, "09:00"),
    time: "09:00",
    ownerId: "u_1",
    ownerName: "Hussain Ali",
    outcome: "Follow-up Needed",
    notes: "Scheduled follow-up on proposal.",
  },
];

export function getCallById(id: string): CallRecord | undefined {
  return callMocks.find((call) => call.id === id);
}

export function callsByOwner(ownerName: string): CallRecord[] {
  return callMocks.filter((call) => call.ownerName === ownerName);
}

export function topCallers() {
  const counts: Record<string, number> = {};
  for (const call of callMocks) {
    counts[call.ownerName] = (counts[call.ownerName] ?? 0) + 1;
  }
  return counts;
}