import type { QuoteStatus, QuoteRecord } from "@/lib/types";
import { iso } from "@/lib/date-utils";

export const quoteStatuses: QuoteStatus[] = [
  "Draft",
  "Sent",
  "Viewed",
  "Accepted",
  "Rejected",
  "Expired",
];

export const quoteMocks: QuoteRecord[] = [
  {
    id: "q_001",
    number: "Q-2024-001",
    customerName: "Techno Solutions",
    companyId: "c_001",
    dealId: "d_001",
    dealName: "Techno Automation Suite",
    issueDate: iso(-5, "10:00"),
    expiryDate: iso(0, "10:00"),
    currency: "USD",
    lineItems: [
      {
        id: "qli_001",
        productId: "pr_001",
        name: "Enterprise Automation Suite",
        quantity: 1,
        unitPrice: 999,
        discount: 0,
        tax: 99.9,
        subtotal: 999,
      },
      {
        id: "qli_002",
        productId: "pr_003",
        name: "Premium Support",
        quantity: 1,
        unitPrice: 199,
        discount: 0,
        tax: 19.9,
        subtotal: 199,
      },
    ],
    subtotal: 1198,
    discount: 0,
    tax: 119.8,
    total: 1317.8,
    status: "Sent",
    terms: "Valid for 30 days",
    notes: "Thank you for your business!",
    createdAt: iso(5, "10:00"),
    timeline: [
      { id: "qt_001", event: "Quote created", at: iso(5, "10:00") },
      { id: "qt_002", event: "Quote sent", at: iso(5, "14:00") },
    ],
  },
  {
    id: "q_002",
    number: "Q-2024-002",
    customerName: "Skyline Retail",
    companyId: "c_006",
    dealId: "d_006",
    dealName: "Skyline Retail Omnichannel",
    issueDate: iso(0, "14:00"),
    expiryDate: iso(15, "14:00"),
    currency: "USD",
    lineItems: [
      {
        id: "qli_003",
        productId: "pr_002",
        name: "Integration Pack",
        quantity: 2,
        unitPrice: 2990,
        discount: 10,
        tax: 538.2,
        subtotal: 5680,
      },
    ],
    subtotal: 5680,
    discount: 568,
    tax: 538.2,
    total: 6442,
    status: "Draft",
    terms: "Valid for 14 days",
    notes: "Pending internal review",
    createdAt: iso(10, "09:00"),
    timeline: [
      { id: "qt_003", event: "Quote drafted", at: iso(10, "09:00") },
    ],
  },
  {
    id: "q_003",
    number: "Q-2024-003",
    customerName: "Nova Systems",
    companyId: "c_003",
    dealId: "d_003",
    dealName: "Nova Cloud Migration",
    issueDate: iso(-10, "16:00"),
    expiryDate: iso(-5, "16:00"),
    currency: "USD",
    lineItems: [
      {
        id: "qli_004",
        productId: "pr_005",
        name: "Basic Plan",
        quantity: 5,
        unitPrice: 29,
        discount: 0,
        tax: 34.8,
        subtotal: 145,
      },
    ],
    subtotal: 145,
    discount: 0,
    tax: 34.8,
    total: 179.8,
    status: "Viewed",
    terms: "Valid for 21 days",
    notes: "Under evaluation by procurement",
    createdAt: iso(8, "11:00"),
    timeline: [
      { id: "qt_004", event: "Quote created", at: iso(8, "11:00") },
      { id: "qt_005", event: "Quote viewed", at: iso(9, "10:00") },
    ],
  },
  {
    id: "q_004",
    number: "Q-2024-004",
    customerName: "Lotus Digital",
    companyId: "c_009",
    dealId: "d_009",
    dealName: "Lotus Digital Agency Suite",
    issueDate: iso(-15, "11:00"),
    expiryDate: iso(-10, "11:00"),
    currency: "USD",
    lineItems: [
      {
        id: "qli_005",
        productId: "pr_004",
        name: "Monthly Subscription",
        quantity: 12,
        unitPrice: 99,
        discount: 0,
        tax: 118.8,
        subtotal: 1188,
      },
    ],
    subtotal: 1188,
    discount: 0,
    tax: 118.8,
    total: 1306.8,
    status: "Accepted",
    terms: "Annual commitment",
    notes: "Customer signed during call",
    createdAt: iso(3, "14:00"),
    timeline: [
      { id: "qt_006", event: "Quote created", at: iso(3, "14:00") },
      { id: "qt_007", event: "Quote accepted", at: iso(4, "10:00") },
    ],
  },
];

export function getQuoteById(id: string): QuoteRecord | undefined {
  return quoteMocks.find((q) => q.id === id);
}