import type { CrmCustomerSuccess, CustomerHealthScore } from "@/lib/types";
import { iso } from "@/lib/date-utils";

export const customerHealthScores: CustomerHealthScore[] = [
  { customerId: "c_001", customerName: "Techno Solutions", healthScore: 92, trend: "up", lastActivity: iso(-1, "10:00"), quarterlyRevenue: 149900, renewalDate: iso(90, "10:00"), riskLevel: "Low", ownerId: "u_1", ownerName: "Hussain Ali" },
  { customerId: "c_002", customerName: "BrightWave", healthScore: 78, trend: "stable", lastActivity: iso(-15, "11:00"), quarterlyRevenue: 87500, renewalDate: iso(60, "11:00"), riskLevel: "Medium", ownerId: "u_5", ownerName: "Ayesha Siddiqui" },
  { customerId: "c_003", customerName: "Nova Systems", healthScore: 95, trend: "up", lastActivity: iso(-5, "14:00"), quarterlyRevenue: 125000, renewalDate: iso(45, "14:00"), riskLevel: "Low", ownerId: "u_3", ownerName: "Sara Ahmed" },
  { customerId: "c_006", customerName: "Skyline Retail", healthScore: 65, trend: "down", lastActivity: iso(-10, "14:00"), quarterlyRevenue: 62000, renewalDate: iso(30, "14:00"), riskLevel: "High", ownerId: "u_4", ownerName: "Zain Malik" },
  { customerId: "c_009", customerName: "Lotus Digital", healthScore: 88, trend: "stable", lastActivity: iso(-5, "11:00"), quarterlyRevenue: 45000, renewalDate: iso(30, "11:00"), riskLevel: "Low", ownerId: "u_2", ownerName: "Ali Khan" },
];

export const customerSuccessMocks: CrmCustomerSuccess[] = [
  {
    id: "cs_001",
    customerId: "c_001",
    customerName: "Techno Solutions",
    contactId: "ct_001",
    contactName: "Ahmed Khan",
    managerId: "u_1",
    managerName: "Hussain Ali",
    quarterlyBusinessReviewDate: iso(15, "10:00"),
    nextRenewalDate: iso(90, "10:00"),
    healthScore: 92,
    trend: "up",
    quarterlyRevenue: 149900,
    upsellOpportunity: "Enterprise Plus add-on",
    churnRisk: "Low",
    csatScore: 94,
    ticketsThisQuarter: 2,
    resolutionRate: 100,
    upsellValue: 29900,
  },
  {
    id: "cs_002",
    customerId: "c_002",
    customerName: "BrightWave",
    contactId: "ct_002",
    contactName: "Sarah Malik",
    managerId: "u_5",
    managerName: "Ayesha Siddiqui",
    quarterlyBusinessReviewDate: iso(30, "11:00"),
    nextRenewalDate: iso(60, "11:00"),
    healthScore: 78,
    trend: "stable",
    quarterlyRevenue: 87500,
    upsellOpportunity: "Integration Pack upgrade",
    churnRisk: "Medium",
    csatScore: 82,
    ticketsThisQuarter: 5,
    resolutionRate: 80,
    upsellValue: 15000,
  },
  {
    id: "cs_003",
    customerId: "c_003",
    customerName: "Nova Systems",
    contactId: "ct_003",
    contactName: "John Smith",
    managerId: "u_3",
    managerName: "Sara Ahmed",
    quarterlyBusinessReviewDate: iso(20, "14:00"),
    nextRenewalDate: iso(45, "14:00"),
    healthScore: 95,
    trend: "up",
    quarterlyRevenue: 125000,
    upsellOpportunity: "Migration services",
    churnRisk: "Low",
    csatScore: 97,
    ticketsThisQuarter: 1,
    resolutionRate: 100,
    upsellValue: 35000,
  },
  {
    id: "cs_004",
    customerId: "c_006",
    customerName: "Skyline Retail",
    contactId: "ct_006",
    contactName: "Omar Farooq",
    managerId: "u_4",
    managerName: "Zain Malik",
    quarterlyBusinessReviewDate: iso(15, "14:00"),
    nextRenewalDate: iso(30, "14:00"),
    healthScore: 65,
    trend: "down",
    quarterlyRevenue: 62000,
    upsellOpportunity: "Premium Support add-on",
    churnRisk: "High",
    csatScore: 61,
    ticketsThisQuarter: 8,
    resolutionRate: 63,
    upsellValue: 10000,
  },
];